- db.json
- src/lib/hooks/useFetch.ts
- src/lib/hooks/useInfiniteFetch.ts
- src/lib/hooks/useModelAccessor.ts
- src/lib/model/InfiniteModelAccessor.ts
- src/lib/model/ModelAccessor.ts
- src/lib/model/NormalModelAccessor.ts
- src/lib/model/types.ts
> feat: return error for useFetch and useInfiniteFetch

- src/__tests__/types.ts
- src/__tests__/useFetch-dedupeInterval.test.tsx
- src/__tests__/useFetch.test.tsx
- src/__tests__/useInfiniteFetch-dedupeInterval.test.tsx
- src/__tests__/utils.ts
- src/lib/hooks/types.ts
- src/lib/hooks/useModelAccessor.ts
- src/lib/model/InfiniteModelAccessor.ts
- src/lib/model/ModelAccessor.ts
- src/lib/model/NormalModelAccessor.ts
- src/lib/utils/getCurrentTime.ts
- src/lib/utils/index.ts
- src/lib/utils/noop.ts
> feat: support dedupeInterval for useFetch

- src/example/App.tsx
- src/example/components/Post.tsx
- src/example/hooks/usePost.ts
- src/example/request.ts
- src/lib/hooks/useModelAccessor.ts
- src/lib/model/InfiniteModelAccessor.ts
- src/lib/model/ModelAccessor.ts
- src/lib/model/NormalModelAccessor.ts
> feat: options apply on the first mounted hook

- src/example/App.tsx
- src/example/components/PostList.tsx
- src/example/model/postModel.ts
- src/lib/model/InfiniteModelAccessor.ts
> fix: ignore revalidating if fetchNext is invoked

- src/example/request.ts
- src/lib/model/InfiniteModelAccessor.ts
> feat: make fetching abortable for infiniteFetch

- src/__tests__/useFetch-revalidateOnFocus.test.tsx
- src/__tests__/useFetch-revalidateOnReconnect.test.tsx
- src/__tests__/useFetch.test.tsx
- src/__tests__/useInfiniteFetch-revalidateOnFocus.test.tsx
- src/__tests__/useInfiniteFetch-revalidateOnReconnect.test.tsx
- src/lib/hooks/useModelAccessor.ts
- src/lib/model/ModelAccessor.ts
All default revalidation options set to `false`
> feat: change default revalidation behavior

- src/__tests__/useFetch-pollingInterval.test.tsx
- src/__tests__/utils.tsx
- src/example/App.tsx
- src/example/components/Post.tsx
- src/example/hooks/usePost.ts
- src/lib/hooks/types.ts
- src/lib/hooks/useModelAccessor.ts
- src/lib/model/ModelAccessor.ts
- src/lib/model/NormalModelAccessor.ts
Support polling for useFetch
- Add testing for `useFetch`
#31
> feat: support polling for useFetch

- src/__tests__/useInfiniteFetch-pollingInterval.test.tsx
- src/example/App.tsx
- src/lib/model/InfiniteModelAccessor.ts
- src/lib/model/ModelAccessor.ts
- src/lib/model/NormalModelAccessor.ts
> feat: support polling for useInfiniteFetch

- src/__tests__/paginationAdapter.test.ts
- src/__tests__/useFetch-pollingInterval.test.tsx
- src/__tests__/useFetch-revalidateIfStale.test.tsx
- src/__tests__/useFetch-revalidateOnFocus.test.tsx
- src/__tests__/useFetch-revalidateOnReconnect.test.tsx
- src/__tests__/useInfiniteFetch-dedupeInterval.test.tsx
- src/__tests__/useInfiniteFetch-pollingInterval.test.tsx
- src/__tests__/useInfiniteFetch-revalidateIfStale.test.tsx
- src/__tests__/useInfiniteFetch-revalidateOnFocus.test.tsx
- src/__tests__/useInfiniteFetch-revalidateOnReconnect.test.tsx
- src/__tests__/useInfiniteFetch.test.tsx
- src/lib/adapters/paginationAdapter.ts
> feat: enhance pagination adapter

- src/__tests__/paginationAdapter.test.ts
- src/lib/adapters/paginationAdapter.ts
> feat: support transform for pagination adapter

- .github/workflows/testing.yml
- package.json
> chore: run pnpm lint when opening pr

- .eslintrc.json
- package.json
- pnpm-lock.yaml
- src/__tests__/useAccessor-infinite-dedupeInterval.test.tsx
> chore: install eslint-react-plugin

- src/lib/constants.ts
- src/lib/hooks/types.ts
- src/lib/hooks/useAccessor.ts
> feat: add revalidateOnMount to options

- src/example/components/Post.tsx
- src/example/hooks/usePost.ts
- src/lib/constants.ts
- src/lib/contexts/AccessorOptionsContext.tsx
- src/lib/contexts/index.ts
- src/lib/hooks/types.ts
- src/lib/hooks/useAccessor.ts
- src/lib/model/Accessor.ts
> fix: allow non-required options

- src/__tests__/useAccessor-infinite-pollingInterval.test.tsx
- src/__tests__/useAccessor-infinite-revalidateIfStale.test.tsx
- src/__tests__/useAccessor-infinite-revalidateOnFocus.test.tsx
- src/__tests__/useAccessor-normal-pollingInterval.test.tsx
- src/__tests__/useAccessor-normal.test.tsx
- src/__tests__/utils.tsx
> fix: remove StrcitMode

- README.md
- src/__tests__/useAccessor-infinite-pollingInterval.test.tsx
- src/__tests__/useAccessor-normal-pollingInterval.test.tsx
> docs: update readme

- .github/workflows/testing.yml
- README.md
- package.json
- pnpm-lock.yaml
> ci: upload coverage

- docs/API/createPaginationAdapter.md
- src/lib/adapters/paginationAdapter.ts
> fix: store original id for PaginationMeta

- src/__tests__/useAccessor-revalidateIfStale.test.tsx
- src/lib/model/Model.ts
- src/lib/model/types.ts
> feat: add setIsStale to accessor creator and model

- docs/API/createPaginationAdapter.md
- src/__tests__/paginationAdapter.test.ts
- src/lib/adapters/paginationAdapter.ts
> feat: support pagination sorting

- src/lib/index.ts
> chore: specify export items explicitly

- src/lib/hooks/types.ts
- src/lib/hooks/useAccessor.ts
> feat: return accessor by useAccessor

- codecov.yml
- src/lib/hooks/types.ts
- src/lib/hooks/useAccessor.ts
> feat: return isLoading by useAccessor

- codecov.yml
- src/__tests__/useAccessor-keepPreviousData.test.tsx
- src/lib/constants.ts
- src/lib/hooks/types.ts
- src/lib/hooks/useAccessor.ts
> feat: support keepPreviousData

- README.md
- docs/api/README.md
- docs/api/classes/Accessor.md
- docs/api/classes/InfiniteAccessor.md
- docs/api/classes/NormalAccessor.md
- docs/api/interfaces/AccessorOptions.md
- docs/api/interfaces/AccessorOptionsProviderProps.md
- docs/api/interfaces/InfiniteAccessorCreator.md
- docs/api/interfaces/InfiniteAction.md
- docs/api/interfaces/NormalAccessorCreator.md
- docs/api/interfaces/NormalAction.md
- docs/api/interfaces/Pagination.md
- docs/api/interfaces/PaginationAdapter.md
- docs/api/interfaces/PaginationMeta.md
- docs/api/interfaces/PaginationState.md
- src/__tests__/utils.tsx
- src/example/model/postModel.ts
- src/lib/model/InfiniteAccessor.ts
- src/lib/model/Model.ts
- src/lib/model/NormalAccessor.ts
> refactor: separate defineAccessor to defineNormalAccessor and defineInfiniteAccessor

- docs/api/README.md
- docs/api/classes/Accessor.md
- docs/api/classes/InfiniteAccessor.md
- docs/api/classes/NormalAccessor.md
- docs/api/interfaces/AccessorOptions.md
- docs/api/interfaces/AccessorOptionsProviderProps.md
- docs/api/interfaces/InfiniteAccessorCreator.md
- docs/api/interfaces/InfiniteAction.md
- docs/api/interfaces/NormalAccessorCreator.md
- docs/api/interfaces/NormalAction.md
- docs/api/interfaces/Pagination.md
- docs/api/interfaces/PaginationAdapter.md
- docs/api/interfaces/PaginationMeta.md
- docs/api/interfaces/PaginationState.md
- docs/api/interfaces/ServerStateKeyProviderProps.md
- src/__tests__/useAccessor-revalidateIfStale.test.tsx
- src/lib/hooks/types.ts
- src/lib/hooks/useAccessor.ts
- src/lib/model/Accessor.ts
- src/lib/model/Model.ts
> refactor: replace setIsStale with invalidate

- README.md
- docs/api/README.md
- docs/api/classes/Accessor.md
- docs/api/classes/InfiniteAccessor.md
- docs/api/classes/NormalAccessor.md
- docs/api/interfaces/AccessorOptions.md
- docs/api/interfaces/AccessorOptionsProviderProps.md
- docs/api/interfaces/InfiniteAccessorCreator.md
- docs/api/interfaces/InfiniteAction.md
- docs/api/interfaces/NormalAccessorCreator.md
- docs/api/interfaces/NormalAction.md
- docs/api/interfaces/Pagination.md
- docs/api/interfaces/PaginationAdapter.md
- docs/api/interfaces/PaginationMeta.md
- docs/api/interfaces/PaginationState.md
- docs/api/interfaces/ServerStateKeyProviderProps.md
- package.json
The new name has been determined!
> feat: use new name

- src/lib/model/Accessor.ts
- src/lib/model/InfiniteAccessor.ts
- src/lib/model/NormalAccessor.ts
> refactor: rename onFetchingSuccess to onFetchingFinish

- src/lib/contexts/AccessorOptionsContext.tsx
> fix: memo the accessor options in provider

- docs/api/README.md
- docs/api/classes/Accessor.md
- docs/api/classes/InfiniteAccessor.md
- docs/api/classes/NormalAccessor.md
- docs/api/interfaces/AccessorOptions.md
- docs/api/interfaces/AccessorOptionsProviderProps.md
- docs/api/interfaces/InfiniteAccessorCreator.md
- docs/api/interfaces/InfiniteAction.md
- docs/api/interfaces/NormalAccessorCreator.md
- docs/api/interfaces/NormalAction.md
- docs/api/interfaces/Pagination.md
- docs/api/interfaces/PaginationAdapter.md
- docs/api/interfaces/PaginationMeta.md
- docs/api/interfaces/PaginationState.md
- docs/api/interfaces/ServerStateKeyProviderProps.md
- src/example/App.tsx
- src/example/components/Post.tsx
- src/example/components/PostList.tsx
- src/example/components/index.ts
- src/example/hooks/index.ts
- src/example/hooks/usePost.ts
- src/example/main.tsx
- src/example/model/index.ts
- src/example/model/postModel.ts
- src/example/request.ts
- src/lib/hooks/types.ts
- src/lib/hooks/useAccessor.ts
- src/lib/hooks/useHydrate.ts
> docs: update tsdoc to update api documentation

- docs/api/interfaces/PaginationAdapter.md
- src/lib/adapters/paginationAdapter.ts
❌  is not existed
✅ is non-existent
✅ does not exist
is not existed -> does not exist
> chore: correct english grammer

- src/__tests__/useModel.test.ts
- src/lib/hooks/index.ts
- src/lib/hooks/useModel.ts
- src/lib/index.ts
- src/lib/model/Model.ts
> feat: support useModel

- .eslintrc.json
- docs/api/README.md
- docs/api/classes/Accessor.md
- docs/api/classes/InfiniteAccessor.md
- docs/api/classes/NormalAccessor.md
- docs/api/interfaces/AccessorOptions.md
- docs/api/interfaces/AccessorOptionsProviderProps.md
- docs/api/interfaces/InfiniteAccessorCreator.md
- docs/api/interfaces/InfiniteAction.md
- docs/api/interfaces/NormalAccessorCreator.md
- docs/api/interfaces/NormalAction.md
- docs/api/interfaces/Pagination.md
- docs/api/interfaces/PaginationAdapter.md
- docs/api/interfaces/PaginationMeta.md
- docs/api/interfaces/PaginationState.md
- docs/api/interfaces/ServerStateKeyProviderProps.md
- src/__tests__/InfiniteAccessor.test.ts
- src/__tests__/NormalAccessor.test.ts
- src/example/model/postModel.ts
- src/lib/index.ts
- src/lib/model/Accessor.ts
- src/lib/model/InfiniteAccessor.ts
- src/lib/model/Model.ts
- src/lib/model/NormalAccessor.ts
> feat: return array of data and error for revalidate and fetchNext

- src/lib/model/Model.ts
invalidate prefix by `1` may also invalidate `10/xxxx`
> fix(model): ensure to invalidate the correct acessor cache key

- src/__tests__/accessorCreator.test.ts
- src/lib/model/Accessor.ts
- src/lib/model/InfiniteAccessor.ts
- src/lib/model/Model.ts
- src/lib/model/NormalAccessor.ts
- src/lib/model/types.ts
> fix: remove idle accessor

- package.json
> chore: update version to 0.5.0

- src/__tests__/InfiniteAccessor.test.ts
- src/lib/model/InfiniteAccessor.ts
- src/lib/model/Model.ts
- src/lib/model/types.ts
> fix: record the pages number for infinite accessor

- package.json
> chore: update version to 0.5.1

- src/lib/model/InfiniteAccessor.ts
- src/lib/model/NormalAccessor.ts
- src/lib/model/types.ts
> feat: add getState to fetchData

- src/lib/adapters/paginationAdapter.ts
> feat: provide merge for pagination adapter

- src/lib/model/types.ts
> refactor: rename meta to context

- src/lib/hooks/types.ts
- src/lib/hooks/useAccessor.ts
- src/lib/hooks/useLazyAccessor.ts
- src/lib/model/Accessor.ts
- src/lib/model/InfiniteAccessor.ts
- src/lib/model/Model.ts
- src/lib/model/NormalAccessor.ts
- src/lib/model/types.ts
Move the general logic to `onFetchingFinish`.
> refactor: handle general task in onFetchingFinish

- src/__tests__/useAccessor-normal-pollingInterval.test.tsx
- src/lib/constants.ts
- src/lib/hooks/types.ts
- src/lib/model/Accessor.ts
> feat: support pollingWhenHidden

- packages/daxus/src/__tests__/useAccessor-autoModel.test.tsx
- packages/daxus/src/__tests__/useSuspenseAccessor.test.tsx
- packages/daxus/src/__tests__/utils.tsx
- packages/daxus/src/example/model/postModel.ts
- packages/daxus/src/lib/hooks/types.ts
- packages/daxus/src/lib/hooks/useAccessor.ts
- packages/daxus/src/lib/hooks/useSuspenseAccessor.ts
- packages/daxus/src/lib/index.ts
- packages/daxus/src/lib/model/Accessor.ts
- packages/daxus/src/lib/model/BaseAccessor.ts
- packages/daxus/src/lib/model/InfiniteAccessor.ts
- packages/daxus/src/lib/model/Model.ts
- packages/daxus/src/lib/model/NormalAccessor.ts
- packages/daxus/src/lib/model/index.ts
- pnpm-lock.yaml
> refactor(daxus): rename Accessor to BaseAccessor

- packages/daxus/src/model/Model.ts
> refactor(daxus): add compositeSetStale to reduce repeated code

- packages/daxus/README.md
- packages/daxus/src/model/Model.ts
> docs(daxus): add readme

- packages/daxus/src/model/Model.ts
> refactor(daxus): return cached accessor earlier in accessor creator

- packages/daxus/src/__tests__/Accessor.test.ts
- packages/daxus/src/__tests__/accessorCreator.test.ts
- packages/daxus/src/__tests__/useAccessor-autoModel.test.tsx
- packages/daxus/src/__tests__/useAccessor-conditional.test.tsx
- packages/daxus/src/__tests__/useAccessor-dedupeInterval.test.tsx
- packages/daxus/src/__tests__/useAccessor-keepPreviousData.test.tsx
- packages/daxus/src/__tests__/useAccessor-pollingInterval.test.tsx
- packages/daxus/src/__tests__/useAccessor-revalidateIfStale.test.tsx
- packages/daxus/src/__tests__/useAccessor-revalidateOnFocus.test.tsx
- packages/daxus/src/__tests__/useAccessor-revalidateOnMount.test.tsx
- packages/daxus/src/__tests__/useAccessor-revalidateOnReconnect.test.tsx
- packages/daxus/src/__tests__/useAccessor.test.tsx
- packages/daxus/src/__tests__/useSuspenseAccessor.test.tsx
- packages/daxus/src/hooks/useAccessor.ts
- packages/daxus/src/index.ts
- packages/daxus/src/model/Accessor.ts
- packages/daxus/src/model/Model.ts
- packages/daxus/src/model/types.ts
> refactor(daxus): delete normal word

- packages/daxus/src/model/Model.ts
> fix(daxus): don't call window too early

- README.md
- docs/accessor.md
- docs/pagination.md
- examples/simple-forum/modules/post/model.ts
- packages/daxus/src/__tests__/paginationAdapter.test.ts
- packages/daxus/src/__tests__/utils.tsx
- packages/daxus/src/adapters/paginationAdapter.ts
> refactor(daxus): change initialState to getInitialState

- packages/daxus/src/__tests__/createPaginationState.test.ts
- packages/daxus/src/adapters/createPaginationState.ts
- packages/daxus/src/adapters/index.ts
- packages/daxus/src/index.ts
> feat(daxus): add createPaginationState

- package.json
- packages/daxus/src/__tests__/createModel.test.ts
- packages/daxus/src/model/createModel.ts
> fix(daxus): close  #277

- packages/daxus/src/__tests__/InfiniteAccessor.test.ts
- packages/daxus/src/__tests__/types.ts
- packages/daxus/src/__tests__/utils.tsx
- packages/daxus/src/model/InfiniteAccessor.ts
> feat(daxus): add isEnd to InfiniteAccessor

- packages/daxus/src/__tests__/Accessor.test.ts
- packages/daxus/src/model/BaseAccessor.ts
To allow users returning boolean value
> fix(daxus): check null strictly
