README.md, src/components/PostList.tsx, src/hooks/usePost.ts, src/lib/model/Model.ts, src/lib/model/types.ts, src/model/postModel.ts
This pr add `createModel` to make the api more easy to use.
=> refactor: make api more easy

.github/workflows/testing.yml, src/__tests__/paginationAdapter.test.ts, src/__tests__/types.ts, src/example/components/PostList.tsx, src/example/model/postModel.ts, src/lib/adapters/paginationAdapter.ts, src/lib/model/types.ts, src/lib/utils/isNonNullable.ts
Now `adapter.readPagination` will return the following data structure: 
```ts
type Return = {
items: Data[],
noMore: boolean,
sizePerPage: number
}
```
=> feat: add readPagination to return items and meta

src/lib/hooks/useUpdatedRef.ts
see the pitfall in https://react.dev/reference/react/useRef#referencing-a-value-with-a-ref
=> fix: update ref in useEffect

src/__tests__/useInfiniteFetch-revalidateOnFocus.test.tsx
When revalidation and fetching next page are triggered concurrently, we should abort the revalidation and execute fetching next page.
=> test: add revalidate and fetching next page testing

src/lib/model/ModelAccessor.ts
In event listener, check whether the `revalidateOnFocus` / `revalidateOnReconnect` is `true` instead of registering by them.
=> fix: check revalidateOnFocus/Reconnect when even emit

src/lib/hooks/types.ts, src/lib/hooks/useFetch.ts, src/lib/hooks/useInfiniteFetch.ts, src/lib/hooks/useModelAccessor.ts
Return `revalidate` such that developer can manually determine when to revalidate the data.
=> feat: return revalidate for each hook

src/__tests__/useHydrate.test.tsx, src/lib/hooks/index.ts, src/lib/hooks/useHydrate.ts
`useHydrate` will depend on the first argument (called `data`). It is the data you want to hydrate. you should make sure it is an object and cannot change with every render. It should either be the top level props (like nextjs's `getServerProps`) or be wrapped with react's `useMemo`.
The second argument is the update function. It will be executed whenever the first argument changes. Note that it will be invoked only once for each data.
#16
=> feat: add useHydrate to support ssr

src/__tests__/InfiniteAccessor.test.ts, src/__tests__/NormalAccessor.test.ts, src/__tests__/paginationAdapter.test.ts, src/__tests__/types.ts, src/__tests__/useAccessor-infinite-pollingInterval.test.tsx, src/__tests__/useAccessor-infinite-revalidateOnFocus.test.tsx, src/__tests__/useAccessor-infinite-revalidateOnReconnect.test.tsx, src/__tests__/useAccessor-infinite.test.tsx, src/__tests__/useAccessor-normal-dedupeInterval.test.tsx, src/__tests__/useAccessor-normal-pollingInterval.test.tsx, src/__tests__/useAccessor-normal-revalidateOnFocus.test.tsx, src/__tests__/useAccessor-normal-revalidateOnReconnect.test.tsx, src/__tests__/useAccessor-normal.test.tsx, src/__tests__/useHydrate.test.tsx, src/__tests__/utils.tsx, src/lib/model/Accessor.ts, src/lib/model/InfiniteAccessor.ts, src/lib/model/NormalAccessor.ts
For `NormalAccessor`, `revalidate` now will return the promise which can be the data or `null`. It will be `null` when it is deduped.
`InfiniteAccessor` will return an array contains each page. Also, the `fetchNext` will return the same promise now.
#54
=> feat: return useful promise for accessor.revalidate and fetchNext

src/__tests__/paginationAdapter.test.ts, src/__tests__/useAccessor-infinite-dedupeInterval.test.tsx, src/__tests__/useAccessor-infinite-pollingInterval.test.tsx, src/__tests__/useAccessor-infinite-revalidateIfStale.test.tsx, src/__tests__/useAccessor-infinite-revalidateOnFocus.test.tsx, src/__tests__/useAccessor-infinite-revalidateOnReconnect.test.tsx, src/__tests__/useAccessor-infinite.test.tsx, src/__tests__/useAccessor-normal-dedupeInterval.test.tsx, src/__tests__/useAccessor-normal-revalidateIfStale.test.tsx, src/__tests__/useAccessor-normal.test.tsx, src/__tests__/utils.tsx, src/example/components/PostList.tsx, src/example/hooks/usePost.ts, src/example/model/postModel.ts, src/lib/adapters/paginationAdapter.ts, src/lib/hooks/useAccessor.ts, src/lib/model/Accessor.ts, src/lib/model/InfiniteAccessor.ts, src/lib/model/Model.ts, src/lib/model/NormalAccessor.ts, src/lib/model/types.ts
The inner state should be called `state` instead of `model`. This is a breaking change since `getModel` cannot be used now.
close #73
=> refactor: inner state should be called state instead of model

src/__tests__/paginationAdapter.test.ts, src/lib/adapters/paginationAdapter.ts
Since the object key would be transformed to string type, this pr transform all id parameter to string.
=> feat: transform all id to string

src/__tests__/useAccessor-infinite-revalidateOnMount.test.tsx, src/__tests__/useAccessor-normal-revalidateOnMount.test.tsx, src/__tests__/useAccessor-revalidateIfStale.test.tsx, src/lib/constants.ts, src/lib/hooks/types.ts, src/lib/hooks/useAccessor.ts, src/lib/model/Accessor.ts
Developer now can set the data, for which the accessor is responsible for fetching, to stale such that the `useAccessor` can determine whether it should revalidate the stale data.
close #75
=> feat: support setIsStale and getIsStale

src/__tests__/createModel.test.ts, src/lib/contexts/ServerStateKeyContext.tsx, src/lib/contexts/index.ts, src/lib/hooks/useAccessor.ts, src/lib/hooks/useHydrate.ts, src/lib/index.ts, src/lib/model/Accessor.ts, src/lib/model/InfiniteAccessor.ts, src/lib/model/Model.ts, src/lib/model/NormalAccessor.ts, src/lib/utils/index.ts, src/lib/utils/isServer.ts
Use `ServerStateKeyProvider` to let developers update the server state but don't cause state pollution.
#16
=> feat: add serverStateKey for model

docs/api/README.md, docs/api/classes/Accessor.md, docs/api/classes/InfiniteAccessor.md, docs/api/classes/NormalAccessor.md, docs/api/interfaces/AccessorOptions.md, docs/api/interfaces/AccessorOptionsProviderProps.md, docs/api/interfaces/InfiniteAccessorCreator.md, docs/api/interfaces/InfiniteAction.md, docs/api/interfaces/NormalAccessorCreator.md, docs/api/interfaces/NormalAction.md, docs/api/interfaces/Pagination.md, docs/api/interfaces/PaginationAdapter.md, docs/api/interfaces/PaginationMeta.md, docs/api/interfaces/PaginationState.md, docs/api/interfaces/ServerStateKeyProviderProps.md, src/lib/contexts/ServerStateKeyContext.tsx
Developers now do not need to pass server state key.
=> feat: ServerStateKey provide an object internally

src/lib/model/Model.ts
=> fix: should early return

docs/api/README.md, docs/api/classes/Accessor.md, docs/api/classes/InfiniteAccessor.md, docs/api/classes/NormalAccessor.md, docs/api/interfaces/AccessorOptions.md, docs/api/interfaces/AccessorOptionsProviderProps.md, docs/api/interfaces/InfiniteAccessorCreator.md, docs/api/interfaces/InfiniteAction.md, docs/api/interfaces/NormalAccessorCreator.md, docs/api/interfaces/NormalAction.md, docs/api/interfaces/Pagination.md, docs/api/interfaces/PaginationAdapter.md, docs/api/interfaces/PaginationMeta.md, docs/api/interfaces/PaginationState.md, docs/api/interfaces/ServerStateKeyProviderProps.md, src/__tests__/useLazyAccessor.test.tsx, src/lib/model/Accessor.ts, src/lib/model/InfiniteAccessor.ts, src/lib/model/Model.ts, src/lib/model/NormalAccessor.ts, src/lib/model/types.ts
=> fix: notify lazy accessor itself only

src/__tests__/useLazyAccessor.test.tsx, src/lib/hooks/types.ts, src/lib/hooks/useLazyAccessor.ts
=> BREAKING: add LazyAccessorOptions

src/lib/hooks/useHydrate.ts
=> feat: allow undefined for useHydrate

src/__tests__/utils.tsx, src/lib/model/Model.ts
=> BREAKING: change defineAccessor's generic order

src/__tests__/useSuspenseAccessor.test.tsx, src/lib/hooks/index.ts, src/lib/hooks/useAccessor.ts, src/lib/hooks/useSuspenseAccessor.ts, src/lib/index.ts, src/lib/model/Accessor.ts, src/lib/model/InfiniteAccessor.ts, src/lib/model/NormalAccessor.ts, src/lib/model/types.ts, src/lib/utils/index.ts, src/lib/utils/isNonUndefined.ts, src/lib/utils/types.ts
Since the logic is quite different when we want to use `Suspense`, I add a new API to achieve the goal.
This hook doesn't support streaming rendering out of box when using nextjs, we need to create another package to leverage it with nextjs.
#182
=> feat: add useSuspenseAccessor

examples/next-streaming-rendering/app/page.tsx, examples/next-streaming-rendering/package.json, packages/daxus-next/package.json, packages/daxus-next/src/StreamHydration.tsx, packages/daxus-next/src/index.ts, packages/daxus-next/tsconfig.json, packages/daxus/src/__tests__/useAccessor-autoModel.test.tsx, packages/daxus/src/__tests__/useSuspenseAccessor.test.tsx, packages/daxus/src/__tests__/utils.tsx, packages/daxus/src/lib/contexts/DatabaseContext.tsx, packages/daxus/src/lib/contexts/ServerStateKeyContext.tsx, packages/daxus/src/lib/contexts/index.ts, packages/daxus/src/lib/index.ts, packages/daxus/src/lib/model/Accessor.ts, packages/daxus/src/lib/model/InfiniteAccessor.ts, packages/daxus/src/lib/model/Model.ts, packages/daxus/src/lib/model/NormalAccessor.ts, packages/daxus/src/lib/model/createDatabase.ts, packages/daxus/src/lib/model/index.ts, packages/daxus/src/lib/model/types.ts, packages/daxus/src/lib/utils/getKey.ts, pnpm-lock.yaml
This pr refactored the usage of daxus, and support streaming rendering for nextjs.
I introduced a new api `createDatabase` to create a centralized state manager. Developers now should create model with the database and they need to provide a name to their model and their accessor creator. This may be useful when we want to build a dev tool.
For streaming rendering, we subscribe the database. When the model's state change, it would notify our listener.
#182
=> feat: support streaming rendering for nextjs

packages/daxus/src/__tests__/useAccessor-revalidateIfStale.test.tsx, packages/daxus/src/constants.ts, packages/daxus/src/hooks/types.ts, packages/daxus/src/hooks/useAccessor.ts, packages/daxus/src/model/Accessor.ts, packages/daxus/src/model/BaseAccessor.ts, packages/daxus/src/model/InfiniteAccessor.ts, packages/daxus/src/model/Model.ts, packages/daxus/src/model/types.ts
Support `staleTime`
close #92 
Since accessors may be deleted from cache, we need to save the stale time in the model.
=> feat(daxus): support staleTime

packages/daxus/src/__tests__/InfiniteAccessor.test.ts, packages/daxus/src/model/BaseAccessor.ts, packages/daxus/src/model/InfiniteAccessor.ts
=> feat(daxus): add pageNum to revalidate context

packages/daxus/src/__tests__/useAccessor.test.tsx, packages/daxus/src/model/BaseAccessor.ts
Should update the status before invoke listeners.
=> fix(daxus): update the status correctly

packages/daxus/src/__tests__/Accessor.test.ts, packages/daxus/src/__tests__/InfiniteAccessor.test.ts, packages/daxus/src/errors.ts, packages/daxus/src/model/Accessor.ts, packages/daxus/src/model/InfiniteAccessor.ts
The user passed function (like syncState) may cause error. We should throw these error, otherwise it would cause the following error:
```
TypeError: Chaining cycle detected for promise
```
=> fix(daxus): ignore FetchAbortedError only

packages/daxus/src/__tests__/InfiniteAccessor.test.ts, packages/daxus/src/__tests__/createPaginationState.test.ts, packages/daxus/src/adapters/createPaginationState.ts, packages/daxus/src/model/InfiniteAccessor.ts
Whether the pagination is ended should be determined by the users. As a result, the pagination should add a field to record it. The users may want to record something else, so I add a field to allow user to customize it.
=> feat(daxus): support meta for pagination

packages/daxus/src/model/InfiniteAccessor.ts, packages/daxus/src/model/createModel.ts, packages/daxus/src/model/types.ts
When fetching the next page, the infinite accessor would need the data to get the previous page. As a result, we need to record the data instead of the page number.
=> fix(daxus): record data to fetch page correctly
